export const Images = {
  // Background
  imgDaThuong: require('../Images/Backgrounds/ImageDaThuong.png'),
  imgDaKho: require('../Images/Backgrounds/ImageDaKho.png'),
  imgDaHonHop: require('../Images/Backgrounds/ImageDaHonHop.png'),
  imgDaNhayCam: require('../Images/Backgrounds/ImageDaNhayCam.png'),
  imgDaDau: require('../Images/Backgrounds/ImageDaDau.png'),
  imageAvatar1: require('../Images/Backgrounds/Avatar1.png'),
  imageAvatar2: require('../Images/Backgrounds/Avatar2.png'),
  imageHeaderQuickAlert: require('../Images/Backgrounds/HeaderQuickAlert.png'),
  imageHeaderAlert: require('../Images/Backgrounds/HeaderAlert.png'),
  imageVoucherGreen: require('../Images/Backgrounds/VoucherGreen.png'),
  imageVoucherPurple: require('../Images/Backgrounds/VoucherPurple.png'),
  imageVoucherYellow: require('../Images/Backgrounds/VoucherYellow.png'),
  imageBarCode: require('../Images/Backgrounds/Barcode.png'),

  // Menu Images
  iconDaXa: require('../Images/Icons/DauXa.png'),
  iconDuongThe: require('../Images/Icons/DuongThe.png'),
  iconGelDuong: require('../Images/Icons/GelDuong.png'),
  iconKemDuong: require('../Images/Icons/KemDuong.png'),
  iconMatNa: require('../Images/Icons/MatNa.png'),
  iconSuaRuaMat: require('../Images/Icons/SuaRuaMat.png'),
  iconSuaTam: require('../Images/Icons/SuaTam.png'),
  iconTinhChat: require('../Images/Icons/TinhChat.png'),

  // Skin type
  iconDaThuong: require('../Images/Icons/DaThuong.png'),
  iconDaKho: require('../Images/Icons/DaKho.png'),
  iconDaNhayCam: require('../Images/Icons/DaNhayCam.png'),
  iconDaDau: require('../Images/Icons/DaDau.png'),
  iconDaHonHop: require('../Images/Icons/DaHonHop.png'),
  iconDaMun: require('../Images/Icons/DaMun.png'),

  // Icons
  iconLogoNew: require('../Images/Icons/LogoNew.png'),
  iconLogo: require('../Images/Icons/Logo.png'),
  iconDaySakiText: require('../Images/Icons/Daysaki.png'),
  iconBuy: require('../Images/Icons/Buy.png'),
  iconFace: require('../Images/Icons/Face.png'),
  iconSearch: require('../Images/Icons/Search.png'),
  iconX: require('../Images/Icons/iconX.png'),
  iconPinkTick: require('../Images/Icons/PinkTick.png'),
  iconPinkPlus: require('../Images/Icons/PinkPlus.png'),
  iconArrowLeft: require('../Images/Icons/ArrowLeft.png'),
  iconStar: require('../Images/Icons/Star.png'),
  iconPlus: require('../Images/Icons/Plus.png'),
  iconMinus: require('../Images/Icons/Minus.png'),
  iconMoMo: require('../Images/Icons/MoMo.png'),
  iconZaLoPay: require('../Images/Icons/ZaLoPay.png'),
  iconCreditCard: require('../Images/Icons/CreditCard.png'),
  iconDiscount: require('../Images/Icons/Discount.png'),
  iconScan: require('../Images/Icons/Scan.png'),
  iconGreenTick: require('../Images/Icons/GreenTick.png'),
  iconFlag: require('../Images/Icons/Flag.png'),
  iconArrowRight: require('../Images/Icons/ArrowRight.png'),
  iconShowPasswordEyes: require('../Images/Icons/ShowPasswordEyes.png'),
  iconHidePasswordEyes: require('../Images/Icons/HidePasswordEyes.png'),
  iconCOD: require('../Images/Icons/COD.png'),
  iconBee: require('../Images/Icons/bee_logo.png'),
  beeShop: require('../Images/Icons/beeShop.png'),
};
